# Generated by Django 4.2.5 on 2023-09-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_sugerida', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('fecha_estreno', models.IntegerField()),
            ],
        ),
    ]
